// ============================================================
//  ZeroTrust Browser — user.js
//  Version: 2.4.0
//  Applied to the ZeroTrust dedicated Firefox profile.
//  DO NOT EDIT manually — regenerated by installer on each run.
// ============================================================

// ── Network / DNS ────────────────────────────────────────────
user_pref("network.trr.mode",                                           3);
user_pref("network.trr.uri",                                            "https://cloudflare-dns.com/dns-query");
user_pref("network.trr.bootstrapAddress",                               "1.1.1.1");
user_pref("network.dns.disablePrefetch",                                true);
user_pref("network.prefetch-next",                                      false);
user_pref("network.http.speculative-parallel-limit",                    0);
user_pref("network.predictor.enabled",                                  false);
user_pref("network.http.http2.enabled",                                 true);
user_pref("network.http.http3.enabled",                                 true);
user_pref("network.http.max-connections",                               900);
user_pref("network.dnsCacheEntries",                                    1000);
user_pref("network.dnsCacheExpiration",                                 3600);

// ── HTTPS / TLS ──────────────────────────────────────────────
user_pref("dom.security.https_only_mode",                               true);
user_pref("dom.security.https_only_mode_ever_enabled",                  true);
user_pref("security.tls.version.min",                                   3);
user_pref("security.tls.enable_0rtt_data",                              false);
user_pref("security.ssl.require_safe_negotiation",                      true);
user_pref("security.cert_pinning.enforcement_level",                    2);
user_pref("security.OCSP.require",                                      true);
user_pref("security.pki.crlite_mode",                                   2);

// ── Tracking / Fingerprinting ────────────────────────────────
user_pref("privacy.trackingprotection.enabled",                         true);
user_pref("privacy.trackingprotection.socialtracking.enabled",          true);
user_pref("privacy.trackingprotection.cryptomining.enabled",            true);
user_pref("privacy.trackingprotection.fingerprinting.enabled",          true);
user_pref("privacy.fingerprintingProtection",                           true);
user_pref("privacy.resistFingerprinting",                               false);
user_pref("canvas.poisondata",                                          true);
user_pref("webgl.disabled",                                             false);
user_pref("media.peerconnection.enabled",                               false);

// ── Cookies ──────────────────────────────────────────────────
user_pref("network.cookie.cookieBehavior",                              5);
user_pref("network.cookie.lifetimePolicy",                              2);

// ── Telemetry ────────────────────────────────────────────────
user_pref("datareporting.healthreport.uploadEnabled",                   false);
user_pref("datareporting.policy.dataSubmissionEnabled",                 false);
user_pref("toolkit.telemetry.enabled",                                  false);
user_pref("toolkit.telemetry.unified",                                  false);
user_pref("toolkit.telemetry.archive.enabled",                          false);
user_pref("toolkit.telemetry.newProfilePing.enabled",                   false);
user_pref("toolkit.telemetry.shutdownPingSender.enabled",               false);
user_pref("toolkit.telemetry.updatePing.enabled",                       false);
user_pref("toolkit.telemetry.bhrPing.enabled",                          false);
user_pref("toolkit.telemetry.firstShutdownPing.enabled",                false);
user_pref("browser.ping-centre.telemetry",                              false);
user_pref("app.shield.optoutstudies.enabled",                           false);
user_pref("app.normandy.enabled",                                       false);
user_pref("breakpad.reportURL",                                         "");
user_pref("browser.crashReports.unsubmittedCheck.enabled",              false);

// ── New Tab / Activity Stream — KILL WEATHER + ALL CONTENT ──
// belt-and-suspenders: mozilla.cfg lockPref() is the real kill,
// this is the profile-level fallback.
user_pref("browser.newtabpage.enabled",                                 true);
user_pref("browser.newtabpage.activity-stream.enabled",                 false);
user_pref("browser.newtabpage.activity-stream.showWeather",             false);
user_pref("browser.newtabpage.activity-stream.system.showWeather",      false);
user_pref("browser.newtabpage.activity-stream.feeds.weatherfeed",       false);
user_pref("browser.newtabpage.activity-stream.weather.query",           "");
user_pref("browser.newtabpage.activity-stream.weather.locationSearchEnabled", false);
user_pref("browser.newtabpage.activity-stream.showSponsored",           false);
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites",   false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites",          false);
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights",false);
user_pref("browser.newtabpage.activity-stream.feeds.snippets",          false);
user_pref("browser.newtabpage.activity-stream.feeds.newtabinit",        false);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons",   false);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features", false);

// ── UI ───────────────────────────────────────────────────────
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets",        true);
user_pref("browser.uidensity",                                          1);
user_pref("browser.compactmode.show",                                   true);
user_pref("browser.tabs.animate",                                       false);
user_pref("browser.startup.page",                                       3);
user_pref("browser.startup.homepage",                                   "https://mrichard333.com/start");
user_pref("browser.newtab.preload",                                     false);

// ── Pocket / Mozilla Services ────────────────────────────────
user_pref("extensions.pocket.enabled",                                  false);
user_pref("browser.discovery.enabled",                                  false);
user_pref("extensions.getAddons.showPane",                              false);
user_pref("extensions.htmlaboutaddons.recommendations.enabled",         false);

// ── Performance (auto-tuned by installer, safe defaults here) ─
user_pref("browser.cache.memory.capacity",                              -1);
user_pref("browser.cache.disk.enable",                                  false);
user_pref("browser.sessionstore.interval",                              30000);
user_pref("javascript.options.ion",                                     true);
user_pref("javascript.options.baselinejit",                             true);
user_pref("javascript.options.wasm",                                    true);